name: Run test and create report
description: "run go test -cover and report"

runs:
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github-token }}

    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/tomo1227/dust-devcontainer
        runCmd: |
          go list -f '{{.Dir}}/...' -m | WORKSPACE_DIR=$(pwd) xargs go test -cover -v
