name: Run test and create report
description: "run go test -cover and report"

runs:
  steps:
    # devcontainer起動
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/nmemoto/try-devcontainer-ci
          runCmd: go list -f '{{.Dir}}/...' -m | WORKSPACE_DIR=$(shell pwd) xargs go test -cover -v
