name: Run test and create report
description: "run go test -cover and report"

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
    uses: docker/login-action@v2 
    with:
      registry: ghcr.io
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}

  - name: Build and run Dev Container task
    uses: devcontainers/ci@v0.3
    with:
      imageName: ghcr.io/example/example-devcontainer
      runCmd: |
        # Add multiple commands to run if needed
        make install-packages
        make ci-build
        go list -f '{{.Dir}}/...' -m | WORKSPACE_DIR=$(shell pwd) xargs go test -cover -v
