version: "3.8"
services:
  devcontainer:
    hostname: dust_devcontainer
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 80:8080
    tty: true
