# name: pull-request-test
# on: [pull_request]
# jobs:
#   hello-checkout:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: |
#           ls -al
#       - run: echo "Succeed PR!"

name: pull-request-test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ワークフローの可視化
      - uses: Kesin11/actions-timeline@v2
      # チェックアウト
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Test
        run: |
          ls .github/workflows/actions/
      # 差分を取得
      - name: Get changed files
        id: get_changed_files
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | tr '\n' ' ')
          echo "changed files: $files"
          echo "CHANGED_FILES=$files" >> $GITHUB_OUTPUT
      # Goファイルが変更されているかチェック
      - name: Check go files changed
        id: check_go_files_changed
        run: |
          GO_FILES_CHANGED=false
          for file in ${{ steps.get_changed_files.outputs.CHANGED_FILES }}; do
            if [[ "$file" == *.go || "$file" == go.mod || "$file" == go.sum ]]; then
              echo "GO_FILES_CHANGED=true" >> $GITHUB_OUTPUT
              break
            fi
          done
      # テスト実行＆カバレッジ取得
      - name: Run test and create report
        # if: steps.check_go_files_changed.outputs.GO_FILES_CHANGED == 'true'
        uses: ./.github/workflows/actions/test_coverage.yml
